### ISSUE TITLE
Porting core-sched-stats.py to BabelTrace2

### ISSUE THREAD

**Issue by jbwyatt4** [digitalocean/vmtop#5]
Hi Julian,

May I email you?

One of the projects I am doing is using core-sched-stats.py for a testing framework for CoreSched with Vineeth Pillai.

I noticed that BabelTrace2 was released with better python bindings and I was thinking of porting core-sched-stats.py to it.

You can reach me at jbwyatt4 at gmail.com

**Comment by jdesfossez** [comment]
Hi John,

Sorry I missed this question, but we communicated offline so I am closing this.
And hopefully I have fixed my notifications settings for this repo, so I get updates now.

Thanks,

Julien
